development:
  sessions:
    default:
      database: flatbook_development
      hosts:
        - localhost:27017
      options:
  options:

production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
      options:
        max_retries: 3
